### ISSUE TITLE
tinytuya requests time out

### ISSUE THREAD

**Issue by 41pha1** [jasonacox/tinytuya#18]
When running tinytuya the smartbulb is found and its status is displayed. But when running the wizard or trying to change the status of the light, there is no response. The light works fine with the tuya app and with Alexa. 

Help would be much appreciated as I am running out of ideas myself  :)

**Comment by jasonacox** [comment]
Can you paste the output from the `python -m tinytuya` or the clip from the wizard output?  

Also, do you get a response using the example for smartbulbs here? https://github.com/jasonacox/tinytuya/blob/master/examples/bulb.py

**Comment by 41pha1** [comment]
The clip of tinytuya wizard is:
>Device Listing
>
>[
>    {
>        "name": "Licht",
>        "id": "bf1f9e205bc3aa9da3fcqw",
>        "key": "f983bce23b8e6ff6"
>    }
>]
>
>\>\> Saving list to devices.json
>    1 registered devices saved
>
>Poll local devices? (Y/n): y
>
>Scanning local network for Tuya devices...
>   1 local devices discovered
>
>Polling local devices...
>   [Licht] - 192.168.178.79 - No Response`



python -m tinytuya returns:
>TinyTuya (Tuya device scanner) [1.1.0]
>
>[Loaded devices.json - 1 devices]
>
>Scanning on UDP ports 6666 and 6667 for devices (15 retries)...
>
>Licht [Valid payload]: 192.168.178.79
>    ID = bf1f9e205bc3aa9da3fcqw, Product ID = vygwfiiycwz3o8jv, Version = 3.3
>   Status: {'20': True, '21': 'white', '22': 1000, '23': 1000, '24': '000003e803e8', '25': '000e0d0000000000000000c80000', '26': 0}

bulb.py returns:

>TinyTuya - Smart Bulb RGB Test [1.1.0]
>
>TESTING: Device bf1f9e205bc3aa9da3fcqw at 192.168.178.80 with key f983bce23b8e6ff6 version 3.3
>Traceback (most recent call last):
>  File "bulb.py", line 31, in <module>
>    data = d.status()
>  File "/home/pi/.local/lib/python3.7/site-packages/tinytuya/__init__.py", line 467, in status
>    data = self._send_receive(payload)
>  File "/home/pi/.local/lib/python3.7/site-packages/tinytuya/__init__.py", line 333, in _send_receive
>    self._get_socket(False)
>  File "/home/pi/.local/lib/python3.7/site-packages/tinytuya/__init__.py", line 320, in _get_socket
>    self.socket.connect((self.address, self.port))
>ConnectionRefusedError: [Errno 111] Connection refused

My own test successfully reads the status but fails when trying to set it:

>{'dps': {'20': True, '21': 'white', '22': 1000, '23': 1000, '24': '000003e803e8', '25': '000e0d0000000000000000c80000', '26': 0}}
>Exceeded tinytuya retry limit (5)
>Traceback (most recent call last):
>  File "/home/pi/.local/lib/python3.7/site-packages/tinytuya/__init__.py", line 340, in _send_receive
>    data = self.socket.recv(1024)  # try again
>socket.timeout: timed out
>Traceback (most recent call last):
>  File "wemo.py", line 8, in <module>
>    d.set_colour(25, 25, 255)
> File "/home/pi/.local/lib/python3.7/site-packages/tinytuya/__init__.py", line 779, in set_colour
>    data = self._send_receive(payload)
>  File "/home/pi/.local/lib/python3.7/site-packages/tinytuya/__init__.py", line 340, in _send_receive
>    data = self.socket.recv(1024)  # try again
>socket.timeout: timed out

The code is:

>import tinytuya
>
>d = tinytuya.BulbDevice('bf1f9e205bc3aa9da3fcqw', '192.168.178.79', 'f983bce23b8e6ff6')
>d.set_version(3.3)
>data = d.status()
>print(data)
>d.set_colour(25, 25, 255)

**Comment by DevIOT07** [comment]
Had a similar problem where I could scan and see the device,  but it would not respond to query.
Turns out that if the **deviceID** has **22 chars** instead of 20 there's a little tweak you should do in the code.

`# Connect to Tuya BulbDevice
d = tinytuya.BulbDevice(DEVICEID, DEVICEIP, DEVICEKEY, "device22") # "device22" was added
`
and **right after that line** you have to pass valid dps for your device. 
By looking at your status message, you have my same Type B bulb, so the following dps are in use:

`
d.set_dpsUsed({"20": None, "21": None, "22": None, "23": None, "24": None, "25": None, "26": None, "27": None, "28": None})
`
bulb.py example should now work though the whole test.

### NOTE:
Consider redacting your key before posting.

**Comment by 41pha1** [comment]
Thank you a lot for this suggestion I applied the changes in my code but the error still occurs. This time it passes the warm white stage, without actually changing the status of the light and then fails when trying to turn the lamp off:

>Current Status of Bulb: {'dps': {'20': True, '21': 'colour', '22': 1000, '23': 400, '24': '000003e803e8', '25': '000e0d0000000000000000c80000', '26': 0}, 't': 1610552864}
>
>Warm White Test
>
>Power Control Test
>    Turn off lamp
>Exceeded tinytuya retry limit (5)
>Traceback (most recent call last):
>  File "/home/pi/.local/lib/python3.7/site-packages/tinytuya/__init__.py", line 340, in _send_receive
>    data = self.socket.recv(1024)  # try again
>socket.timeout: timed out
>Traceback (most recent call last):
>  File "bulb.py", line 44, in <module>
>    d.turn_off()
>  File "/home/pi/.local/lib/python3.7/site-packages/tinytuya/__init__.py", line 549, in turn_off
>    self.set_status(False, switch)
>  File "/home/pi/.local/lib/python3.7/site-packages/tinytuya/__init__.py", line 519, in set_status
>    data = self._send_receive(payload)
>  File "/home/pi/.local/lib/python3.7/site-packages/tinytuya/__init__.py", line 340, in _send_receive
>    data = self.socket.recv(1024)  # try again
>socket.timeout: timed out

**Comment by DevIOT07** [comment]
> I applied the changes in my code

Have you tried with the _original_ bulb.py provided in the _examples_ folder and **only** applying the changes above ?
Maybe you changed something else in your code that broke it ?
Your line error does not match original code, and it's off even assuming you added my changes.

**Comment by jasonacox** [comment]
@41pha1 

1. Can you tell us what Smart Bulb you are using?  
2. I see you are using 1.1.0, try to update to the latest version:  

```python
python -m pip install --upgrade tinytuya
```

**Comment by 41pha1** [comment]
@jasonacox 

The bulb's ASIN is B07SPVCG59.
I successfully updated tinytuya, but the results sadly haven't changed at all.

**Comment by 41pha1** [comment]
@DevIOT07 
Yes, I only applied your suggested changes in bulb.py linked by jasonacox in the first comment.

**Comment by DevIOT07** [comment]
> If the bulb is at fault here, i'd be happy to buy a different one. 

In the first comment you said it's working fine with tuya app and Alexa, so I doubt it's the lamps fault.

>Are the any bulbs, that work have been tested to work well with tinytuya?

Here's what I'm using B089LQ4S2G. Looks very similar to yours.
Mac address: 28 : 6d : cd : YY:XX:XX
Hostname : ThingsTurn_XXXX     
mcu > verSw : 1.4.2 

Tested bulb.py script "**TinyTuya - Smart Bulb RGB Test [1.1.2]**" with both python **2.7.9** and python **3.4.2**

Also you said 
>This time it passes the warm white stage, without actually changing the status of the light 

but before the Warm White Test and Power Control Test  there's a Dimmer control test.
What happened to it ?

**Comment by 41pha1** [comment]
@DevIOT07 
I am using this https://github.com/jasonacox/tinytuya/blob/master/examples/bulb.py script with your changes applied. In that version, the Dimmer Control test follows just after the Power Control test. I also had to change.

> d.set_white()

to

>d.set_white(brightness = 255, colourtemp = 100)

for some reason, because I otherwise get the error:

>File "bulb.py", line 44, in <module>
>   d.set_white()
>TypeError: set_white() missing 2 required positional arguments: 'brightness' and 'colourtemp'

Alexa is not plugged in and the bulb has been restarted. I am also not using the Tuya app.

**Comment by jasonacox** [comment]
hi @41pha1 - the odd thing is that d.set_white() has python default set (see below) so it is very odd that you are getting that error.  What version of python are you using?  `python --version `

```python
    def set_white(self, brightness=-1, colourtemp=-1):
        """
        Set white coloured theme of an rgb bulb.

        Args:
            brightness(int): Value for the brightness (A:25-255 or B:10-1000)
            colourtemp(int): Value for the colour temperature (A:0-255, B:0-1000).

            Default: Max Brightness and Min Colourtemp
        """
        # Brightness (default Max)
        if brightness < 0:
            brightness = 255
...
```

**Comment by 41pha1** [comment]
I am using Python 3.7.3 on a Raspberry Pi. I just noticed that bulb.py runs without any issues on Ubuntu 20.04 after applying the changes suggested by @DevIOT07 using Python 3.8.5. I updated Python to 3.8 on the RPi manually but the same error still occurs.

**Comment by jasonacox** [comment]
> TypeError: set_white() missing 2 required positional arguments: 'brightness' and 'colourtemp'

If you are still getting that, it seems like a corrupt python install or some local configuration causing it to ignore default parameter settings?   I tested bulb.py on my Raspberry PI successfully with: 

Python 2.7.13
Python 3.5.3

**Comment by 41pha1** [comment]
I reinstalled raspbian and got it working after installing python 3.8.5 and tinytuya 1.1.3! I still don't know what was causing this, because I was using a pretty fresh install of raspbian that I basically haven't tampered with at all. 

Thanks a lot for providing all the help and suggestions!

**Comment by jasonacox** [comment]
That's great news!  Thanks for the update!
